pipeline { 
     tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "Maven"
    }
    agent any 
    stages {
        stage("checks")
        {
            steps{
                bat '''
                cd HelloWorldMaven
                mvn checkstyle:check
                mvn site
                '''
               
            }
        }
        stage('Build') { 
            steps {
                     script{
                    bat '''cd HelloWorldMaven
                          dir
                       mvn compile '''
                     }
            }
        }
        stage('Test'){
            steps {
                        bat '''
                        cd HelloWorldMaven
                        mvn test'''

            }
        }
         stage('Package'){
            steps {
                        bat "mvn package -X"

            }
        }
        // stage('build && SonarQube analysis') {
        //     steps {
        //         withSonarQubeEnv('sonar.tools.devops.****') {
        //             sh 'sonar-scanner -Dsonar.projectKey=myProject -Dsonar.sources=./src'
        //         }
        //     }
        // }
        // stage("Quality Gate") {
        //     steps {
        //         timeout(time: 1, unit: 'HOURS') {
        //             // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
        //             // true = set pipeline to UNSTABLE, false = don't
        //             // Requires SonarScanner for Jenkins 2.7+
        //             waitForQualityGate abortPipeline: true
        //         }
        //     }
		// 	}
        // stage('Deploy') {
        //     steps {
        //        withMaven(maven : 'apache-maven-3.6.0'){
        //                 sh "mvn deploy"
        //         }

        //     }
        // }
    }
    post{
        always{
            emailext attachLog: true, body: '''Hi,
The current status of build ${BUILD_STATUS} 

Thanks''', subject: 'Recend Build Status', to: 'addipallisivasai@gmail.com'
        }
    }
}
