pipeline { 
     tools {
        maven "Maven"
    }
    environment{
        SONARQUBE_URL='https://sonarcloud.io/'
    }
    agent any 
    stages {
        stage("checks")
        {
            steps{
                bat '''
                cd HelloWorldMaven
                mvn checkstyle:check
                mvn site
                '''
               
            }
        }
        stage('Build') { 
            steps {
                     script{
                    bat '''cd HelloWorldMaven
                          dir
                       mvn compile '''
                     }
            }
        }
          stage('Static code analysis analysis') {
            steps {
               withSonarQubeEnv('sonarqube')
               {
                   bat 'mvn sonar:sonar'
               }
                
            }
        }
        stage('Test'){
            steps {
                script{
                    try{
                        bat '''
                        cd HelloWorldMaven
                        mvn test'''
                    }
                    catch(Exception e)
                    {
                        echo "Test stage if failed due to some failure of test cases"
                        echo "${e.getMessage()}"
                    }
                }

            }
        }
        stage("Publish Test Result")
        {
            steps{
                junit '*/**/target/surefire-reports/TEST-*.xml'

            }
        }
        stage("Archive Artifacts")
        {
            steps{
                archiveArtifacts artifacts: '**/target/*.jar'
            }
        }
         stage('Package'){
            steps {
                        bat "mvn package -X"

            }
        }
      
        // stage("Quality Gate") {
        //     steps {
        //         timeout(time: 1, unit: 'HOURS') {
        //             // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
        //             // true = set pipeline to UNSTABLE, false = don't
        //             // Requires SonarScanner for Jenkins 2.7+
        //             waitForQualityGate abortPipeline: true
        //         }
        //     }
		// 	}
        // stage('Deploy') {
        //     steps {
        //        withMaven(maven : 'apache-maven-3.6.0'){
        //                 sh "mvn deploy"
        //         }

        //     }
        // }
    }
    post{
        always{
            emailext attachLog: true, body: '''Hi,
The current status of build ${BUILD_STATUS} 

Thanks''', subject: 'Recend Build Status', to: 'addipallisivasai@gmail.com'
        }
    }
}
