pipeline { 
     tools {
        maven "Maven"
    }
  
    agent any 
    stages {
        stage("checks")
        {
            steps{
                bat '''
                cd HelloWorldMaven
                mvn checkstyle:check
                mvn site
                '''
               
            }
        }
        stage('Build') { 
            steps {
                     script{
                    bat '''cd HelloWorldMaven
                          dir
                       mvn compile '''
                     }
            }
        }
           stage('SonarQube analysis') {
            steps {
                script {
                    def scannerHome = tool name: 'sonarqubescanner', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
                    withSonarQubeEnv('sonarqube') {
                        // def path='${scannerHome}/bin/sonar-scanner'
                        // bat "${path}"
                        bat '''
                        C:\\ProgramData\\Jenkins\\.jenkins\\tools\\hudson.plugins.sonar.SonarRunnerInstallation\\sonarqubescanner\\bin\\sonar-scanner\
                -Dsonar.projectKey=sivasai-jenkins_assessment\
                 -Dsonar.sources=.\\HelloWorldMaven\\src\
                 -Dsonar.organization=sivasai-jenkins\
                 -Dsonar.login=3cade956570c411a53b32955b9337e4281d5d6fd\
                 '''
    
                    }
                }
            }
        }
        stage('Test'){
            steps {
                script{
                    try{
                        bat '''
                        cd HelloWorldMaven
                        mvn test'''
                    }
                    catch(Exception e)
                    {
                        echo "Test stage if failed due to some failure of test cases"
                        echo "${e.getMessage()}"
                    }
                }

            }
        }
        stage("Publish Test Result")
        {
            steps{
                junit '*/**/target/surefire-reports/TEST-*.xml'

            }
        }
        stage("Archive Artifacts")
        {
            steps{
                archiveArtifacts artifacts: '**/target/*.jar'
            }
        }
         stage('Package'){
            steps {
                        bat "mvn package -X"

            }
        }
      
        // stage("Quality Gate") {
        //     steps {
        //         timeout(time: 1, unit: 'HOURS') {
        //             // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
        //             // true = set pipeline to UNSTABLE, false = don't
        //             // Requires SonarScanner for Jenkins 2.7+
        //             waitForQualityGate abortPipeline: true
        //         }
        //     }
		// 	}
        // stage('Deploy') {
        //     steps {
        //        withMaven(maven : 'apache-maven-3.6.0'){
        //                 sh "mvn deploy"
        //         }

        //     }
        // }
    }
//     post{
//         always{
//             emailext attachLog: true, body: '''Hi,
// The current status of build ${BUILD_STATUS} 

// Thanks''', subject: 'Recend Build Status', to: 'addipallisivasai@gmail.com'
//         }
//     }
}
